[package]
name = "spotify_Predictor"
version = "0.1.0"
edition = "2024"

[dependencies]
linfa = "0.7.0"
linfa-logistic = "0.7.0"
ndarray = "0.15"
csv = "1.1"
serde = {version = "1", features = ["derive"]}